-- initial commit
-- model account begin
CREATE TABLE IF NOT EXISTS ADDRESS();
CREATE TABLE IF NOT EXISTS BUYAGAIN();
CREATE TABLE IF NOT EXISTS CITY();
CREATE TABLE IF NOT EXISTS COUNTRY();
CREATE TABLE IF NOT EXISTS COUPON();
CREATE TABLE IF NOT EXISTS CUSTOMER();
CREATE TABLE IF NOT EXISTS DIGITAL_CONTENT_DEVICE();
CREATE TABLE IF NOT EXISTS LANGUAGE_PREFERENCES();
CREATE TABLE IF NOT EXISTS MESSAGE_CUSTOMER();
CREATE TABLE IF NOT EXISTS ORDER();
CREATE TABLE IF NOT EXISTS PAYMENT();
CREATE TABLE IF NOT EXISTS PRODUCT_VOUCHER();
CREATE TABLE IF NOT EXISTS RETURN_ITEM();
CREATE TABLE IF NOT EXISTS TRACK_ITEM();
CREATE TABLE IF NOT EXISTS TRANSACTION_CUSTOMER();
CREATE TABLE IF NOT EXISTS USER_ACCOUNT();
CREATE TABLE IF NOT EXISTS VAT();

-- model account end